enum SECTION_HOME_PAGE_KEY {
    WHAT_IS_SURF = "WHAT_IS_SURF",
    HOW_IT_WORK = "HOW_IT_WORK",
    BONUS_SPECIALS = "BONUS_SPECIALS",
    ROAD_MAP = 'ROAD_MAP',
    TEAM = "TEAM",
    CONTACT = "CONTACT"
}
export default SECTION_HOME_PAGE_KEY